backend:
  name: github
  repo: javadmasani/Araogya
  branch: main
  base_url: https://decap-cms-oauth.vercel.app

media_folder: "assets/uploads"
public_folder: "/Araogya/assets/uploads"

collections:
  - name: "blog"
    label: "Blogs"
    folder: "_posts"
    create: true
    format: "frontmatter"
    extension: "md"
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"

    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug (english-only)"
        name: "slug"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        required: false

      - label: "Category"
        name: "category"
        widget: "string"
        required: false

      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false

      - label: "Content"
        name: "body"
        widget: "markdown"

      - label: "SEO Title"
        name: "seo_title"
        widget: "string"
        required: false

      - label: "SEO Description"
        name: "seo_description"
        widget: "text"
        required: false

  - name: "reviews"
    label: "Patient Reviews"
    folder: "_reviews"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Patient Name", name: "name", widget: "string", required: false }
      - { label: "Rating", name: "rating", widget: "select", options: ["★★★★★","★★★★☆","★★★☆☆"], default: "★★★★★" }
      - { label: "Review", name: "body", widget: "text" }
      - { label: "Status", name: "status", widget: "select", options: ["pending","approved"], default: "pending" }
